Add pre-commit and fix findings
conda/constructor pull request #601
Opened 2023-01-02 09:59 UTC by dbast

### Description

### Checklist - did you ...

- [ ] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [ ] Add / update necessary tests?
- [ ] Add / update outdated documentation?

2023-01-10 17:20 UTC, jaimergp commented
I am aching to do this with the codebase but it will create conflicts on opened PRs so I am inclined to merge as much as possible before we merge this one to minimize the amount of rebasing hell we need :D

2023-01-11 12:23 UTC, dbast commented
@jaimergp going to strip down the pre-commit config to reduce the amount of changes... more pre-commit hooks in be incrementally added via more PRs.

2023-01-11 14:23 UTC, jaimergp commented on .pre-commit-config.yaml
> +      - id: check-merge-conflict
duplicate! :D
```suggestion
```

2023-01-11 14:25 UTC, jaimergp commented
Ok, that makes more sense. Maybe using `blacken` in the next PR is a good step too.

2023-01-12 07:38 UTC, jezdez commented
@dbast I've just added the precommit.ci app to this repo. https://results.pre-commit.ci/repo/github/51571636

Badge: [![pre-commit.ci status](https://results.pre-commit.ci/badge/github/conda/constructor/main.svg)](https://results.pre-commit.ci/latest/github/conda/constructor/main)

```
[![pre-commit.ci status](https://results.pre-commit.ci/badge/github/conda/constructor/main.svg)](https://results.pre-commit.ci/latest/github/conda/constructor/main)
```

2023-01-12 07:39 UTC, jezdez requested changes

2023-01-12 07:39 UTC, jezdez commented on .github/workflows/main.yml
> +      - uses: pre-commit/action@646c83fcd040023954eafda54b4db0192ce70507 # tag=v3.0.0
```suggestion
```

Not needed with pre-commit.ci anymore.

2023-01-12 08:34 UTC, dbast commented
@jezdez Any idea how to extend the pre-commit,ci to be able to execute hooks that need additional tools? like the shellcheck hook which requires Docker (or in other cases hooks that require golang)? That is pretty easy with the pre-commit action, as there are anyways more tools pre-installed on the action runners and also extending those can be done via an action step running before the pre-commit step.

This repo has many shellscripts as part of the code and as part of the examples and as shellcheck pretty good detects all kind of issues like unquoted variables, posix compatibility, missing error handling etc.

This PR only checks the *example* shell scripts via shellcheck. The shell scripts in code are templated and require rendering before linting them via shell check; that is done in this PR https://github.com/conda/constructor/pull/600

2023-01-12 08:40 UTC, dbast commented
@jezdez we can also invite the (public) renovate bot which to keeps the .pre-commit-config.yml hooks versions updated via PRs it proposes... renovate can also update arbitrary pinning versions, if the right regex pattern are added. That would e.g. help to pin the micromamba version in https://github.com/conda/constructor/pull/605 to have stable CI and have it updated by renovate.

2023-01-12 10:33 UTC, jaimergp commented
What about this alternative? https://pypi.org/project/shellcheck-py/

2023-01-12 12:35 UTC, dbast commented
@jaimergp hah. good finding. trying that.

2023-01-12 16:21 UTC, jezdez approved these changes

2023-01-12 16:43 UTC, merged